# github action
name: Manifest Validate by kyverno

on: [push]

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Run kyverno-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run kyverno
        uses: ./ # Uses an action in the root directory
        with:
          command: |
            git ls-tree HEAD -r ./deployment/ --name-only  | xargs -L 1 echo
            
      - name: Run a one-line script
        run: echo Hello, world!









