apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: sample      # require not default namespace
  labels:
    app.kubernetes.io/name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.21.1  # disallow latest tag
    securityContext:
      runAsUser: 11211   # require no-root user
      runAsNonRoot: true
    livenessProbe:       # require pod probes
      httpGet:
        port: 80
        path: /health
      failureThreshold: 5
      periodSeconds: 5
    readinessProbe:
      httpGet:
        port: 80
        path: /
      failureThreshold: 5
      periodSeconds: 5
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 50Mi
