name: Manifest Validate by kyverno CLI

on: [push]

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Run kyverno
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run kyverno
        uses: ./ # Uses an action in the root directory
        with:
          command: |
            git clone https://github.com/yuuusukeeeee/k8s-policy-validate.git && git ls-tree HEAD -r deployment/ --name-only | xargs -I FILE kyverno apply ./policies --resource=FILE

      - name: Show kyverno Result
        uses: ./ # Uses an action in the root directory
        with:
          command: |
            git ls-tree HEAD -r deployment/ --name-only | xargs -I FILE kyverno apply ./policies --resource=FILE > tmp_result.txt && cat tmp_result.txt
