name: Manifest Validate by kyverno CLI

# プッシュもしくはPull Requestでワークフローをトリガーする
# GitHub Action で特定のディレクトリ配下に変更があったときのみワークフローを実行する
# メインブランチの場合のみ
on:
  push:
    branches:
      - main
    paths:
      - "deployment/**"
  pull_request:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Run kyverno
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run kyverno
        uses: ./ # Uses an action in the root directory
        with:
          command: |
            git clone https://github.com/yuuusukeeeee/k8s-policy-validate.git --depth 1
            echo "###################################################"
            echo "######### Kyverno validate below file. ############"
            echo "###################################################"
            echo ""
            git ls-tree HEAD -r deployment/ --name-only
            echo ""
            echo "###################################################"
            echo "################## Validate Result ################"
            echo "###################################################"
            # git ls-tree HEAD -r deployment/ --name-only | xargs -I FILE kyverno apply ./policies --resource=FILE
            
            git ls-tree HEAD -r deployment/ --name-only > file_list.txt
            FILE_LIST=(`cat file_list.txt`)
            
            for FILE_NAME in "${FILE_LIST[@]}" ;
                do
                  KYVERNO_COMMAND="kyverno apply ./policies/Pod_Security_Standards_Baseline ./policies/Pod_Security_Standards_Restricted -r $FILE_NAME" ;
                  echo $KYVERNO_COMMAND ;
                  kyverno apply ./policies/Pod_Security_Standards_Baseline ./policies/Pod_Security_Standards_Restricted -r $FILE_NAME ;
                  echo "#######################################################"
                done
