name: Manifest Schema Check

# プッシュもしくはPull Requestでワークフローをトリガーする
# GitHub Action で特定のディレクトリ配下に変更があったときのみワークフローを実行する
# メインブランチの場合のみ
on:
  push:
    branches:
      - main
    paths:
      - "deployment/**"
  pull_request:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate manifests in dir1 and dir2
        uses: makocchi-git/actions-k8s-manifests-validate@v1.0.1
        with:
          files: ./deployment
